import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  defaultSidebar: [
    {
      type: 'category',
      label: 'Start Here',
      items: [
        'start-here/what-is-zen-mesh',
        'start-here/how-zen-works',
        'start-here/who-should-use-zen-mesh',
        'start-here/current-status',
        'start-here/plans-and-limits',
        'start-here/concepts',
        'start-here/support',
      ],
    },
    {
      type: 'category',
      label: 'Roadmap',
      items: [
      'product/v1-roadmap',
      'launch/v1-live-truth-matrix',
      'launch/v1-live-evidence-index',
      'launch/post-cloud-publication-plan',
    ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/quick-start',
        'getting-started/customer-journey',
        'getting-started/first-15-minutes',
        'getting-started/installation',
        'getting-started/first-webhook',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/planes',
        'concepts/zen-mesh-concepts',
        'concepts/control-surfaces',
        'concepts/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Install and Runtime',
      items: [
        'install/choose-runtime-path',
        'install/edge-plane',
        'install/kubernetes-edge-plane',
        'install/edge-lite',
        'install/data-plane',
      ],
    },
    {
      type: 'category',
      label: 'Delivery',
      items: [
        'delivery/index',
        'delivery/dead-letter-queue',
        'delivery/replay',
        'delivery/replay-and-recovery',
        'delivery/deduplication',
        'delivery/deduplication-vs-idempotency',
        'delivery/filtering',
        'delivery/fan-out',
        'delivery/idempotency',
        'delivery/routing-and-fan-out',
        'delivery/jsonpath-routing',
        'delivery/jsonpath-transforms',
        'delivery/delivery-failures',
        'delivery/replay-vs-retry',
        'delivery/event-routing',
        'delivery/webhook-reliability',
        'delivery/delivery-guarantee-matrix',
        'delivery/idempotency-retry-matrix',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/three-plane-model',
        'architecture/delivery-modes',
        'architecture/security-model',
        'china-market-architecture',
        'payload-locality-invariant',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'security/index',
        'security/security-capability-validation',
        'security/agent-saas-mtls',
        'security/zenlock-credential-lifecycle',
        'security/ip-allowlisting',
        'security/header-validation',
        'security/cryptographic-enrollment',
        'security/secure-webhook-delivery',
        'security/webhook-access-control',
        'security/tenant-isolation',
        'security/trust-lab',
        'security/security-tiering',
        'security/git-sdk-ssrf-classification',
      ],
    },
    {
      type: 'category',
      label: 'Networking',
      items: [
        'networking/gateway-api-migration',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/adapters',
        'guides/endpoints',
        'guides/sources',
        'guides/stripe',
        'guides/stripe-webhooks-behind-firewall',
        'guides/github',
        'guides/github-webhooks-private-kubernetes',
        'guides/webhooks-private-service-no-inbound',
        'guides/twilio',
        'guides/shopify',
        'guides/custom-webhooks',
        'guides/monitoring',
        'guides/traffic-lifecycle',
        'guides/evidence-and-trust',
        'guides/troubleshooting-first-delivery',
        'guides/destinations',
        'guides/cluster-enrollment',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/upgrades',
        'operations/backups',
        'operations/troubleshooting',
        'operations/operational-faq',
        'operations/agent-operations',
        'operations/agent-operability-test',
        'operations/git-surface-requirements',
        'operations/vercel-domain-misconfig',
      ],
    },
    {
      type: 'category',
      label: 'Runbooks',
      items: [
        'runbooks/edge-lite-install-failure',
        'runbooks/edge-plane-enrollment-failure',
        'runbooks/certificate-renewal-failure',
        'runbooks/plane-readiness-failure',
        'runbooks/evidence-missing',
        'runbooks/inconsistent-state-recovery',
      ],
    },
    {
      type: 'category',
      label: 'Trust',
      items: [
        'trust/index',
        'trust/compliance-coverage',
        'trust/evidence',
        'trust/cis-benchmark-alignment',
      ],
    },
    {
      type: 'category',
      label: 'Evidence',
      items: [
        'evidence/overview',
        'evidence/runtime-convergence',
        'evidence/trust-lifecycle',
        'ai/capability-evidence',
        'ai/compliance-evidence',
        'evidence/validation-map',
        'evidence/completion-evidence',
        'evidence/non-claims',
        'ai/verification',
      ],
    },
    {
      type: 'category',
      label: 'AI Agents',
      items: [
        'ai/overview',
        'ai/security-posture',
        'ai/v1-security-validation-summary',
        'ai/wedge-overview',
        'ai/evidence-schema',
        'ai/non-claims',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/overview',
        'api/status',
        'api/write-safety',
        {
          type: 'category',
          label: 'Runtime APIs',
          items: [
            'api/targets',
            'api/endpoints',
            'api/flows',
            'api/delivery-attempts',
            'api/dlq',
            'api/retry',
            'api/replay',
            'api/traces',
            'api/saved-payloads',
            'api/evidence',
            'api/logs',
          ],
        },
        {
          type: 'category',
          label: 'Platform APIs',
          items: [
            'api/authentication',
            'api/rate-limits',
            'api/fabric-adapters',
          ],
        },
        {
          type: 'category',
          label: 'Guides',
          items: [
            'api/quickstart',
            'api/webhooks',
            'api/events',
            'api/examples',
            'api/idempotency',
            'api/versioning',
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          items: [
            'api/errors',
            'api/pagination',
            'api/openapi',
            'api/changelog',
          ],
        },
        {
          type: 'category',
          label: 'Recipes',
          items: [
            'api/recipes/list-planes-and-adapters/api-recipes-list-planes-and-adapters',
            'api/recipes/create-webhook-endpoint/api-recipes-create-webhook-endpoint',
            'api/recipes/create-target/api-recipes-create-target',
            'api/recipes/create-flow/api-recipes-create-flow',
            'api/recipes/drafts-validate-test-publish/api-recipes-drafts-validate-test-publish',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'MCP',
      items: [
        'mcp/overview',
        'mcp/read-only-v1-policy',
        'mcp/tools',
        'mcp/examples',
        'mcp/authentication-and-mtls',
        'mcp/safety-and-boundaries',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/helm-chart',
        'reference/cli',
        'reference/api',
        'reference/customer-api',
        'reference/mcp',
        'reference/configuration',
        'reference/webhook-delivery-evidence',
        'reference/webhook-observability-and-evidence',
        'reference/delivery-status',
        'reference/webhook-faq',
        'reference/ui-api-map',
        'reference/current-status',
      ],
    },
  ],
};

export default sidebars;
