import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import apiSidebar from './docs/api/reference/sidebar';

const sidebars: SidebarsConfig = {
  defaultSidebar: [
    {
      type: 'category',
      label: 'Start Here',
      items: [
        'start-here/what-is-zen-mesh',
        'start-here/who-should-use-zen-mesh',
        'start-here/current-status',
        'start-here/concepts',
        'start-here/support',
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/quick-start',
        'getting-started/installation',
        'getting-started/first-webhook',
      ],
    },
    {
      type: 'category',
      label: 'Delivery',
      items: [
        'delivery/index',
        'delivery/dead-letter-queue',
        'delivery/replay',
        'delivery/replay-and-recovery',
        'delivery/deduplication',
        'delivery/deduplication-vs-idempotency',
        'delivery/filtering',
        'delivery/fan-out',
        'delivery/idempotency',
        'delivery/routing-and-fan-out',
        'delivery/jsonpath-routing',
        'delivery/jsonpath-transforms',
        'delivery/delivery-failures',
        'delivery/replay-vs-retry',
        'delivery/event-routing',
        'delivery/webhook-reliability',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/three-plane-model',
        'architecture/delivery-modes',
        'architecture/security-model',
        'concepts/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'security/index',
        'security/security-capability-validation',
        'security/agent-saas-mtls',
        'security/zenlock-credential-lifecycle',
        'security/ip-allowlisting',
        'security/header-validation',
        'security/cryptographic-enrollment',
        'security/secure-webhook-delivery',
        'security/webhook-access-control',
        'security/tenant-isolation',
      ],
    },
    {
      type: 'category',
      label: 'Networking',
      items: [
        'networking/gateway-api-migration',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/cluster-enrollment',
        'guides/adapters',
        'guides/destinations',
        'guides/endpoints',
        'guides/sources',
        'guides/stripe',
        'guides/github',
        'guides/custom-webhooks',
        'guides/monitoring',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/upgrades',
        'operations/backups',
        'operations/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Evidence',
      items: [
        'evidence/overview',
        'evidence/runtime-convergence',
        'evidence/trust-lifecycle',
        'ai/capability-evidence',
        'ai/compliance-evidence',
        'evidence/validation-map',
        'evidence/merkle-integrity',
        'evidence/completion-evidence',
        'evidence/non-claims',
        'ai/verification',
      ],
    },
    {
      type: 'category',
      label: 'AI Agents',
      items: [
        'ai/overview',
        'ai/security-posture',
        'ai/wedge-overview',
        'ai/evidence-schema',
        'ai/non-claims',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/overview',
        'api/quickstart',
        'api/examples',
        'api/authentication',
        'api/errors',
        'api/webhooks',
        'api/evidence',
        'api/logs',
        'api/events',
        'api/idempotency',
        'api/replay',
        'api/versioning',
        'api/rate-limits',
        'api/changelog',
        ...apiSidebar,
      ],
    },
    {
      type: 'category',
      label: 'MCP',
      items: [
        'mcp/overview',
        'mcp/read-only-v1-policy',
        'mcp/tools',
        'mcp/examples',
        'mcp/authentication-and-mtls',
        'mcp/authentication',
        'mcp/safety-and-boundaries',
        'mcp/draft-system',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/helm-chart',
        'reference/cli',
        'reference/api',
        'reference/customer-api',
        'reference/mcp',
        'reference/configuration',
        'reference/webhook-delivery-evidence',
        'reference/webhook-observability-and-evidence',
        'reference/delivery-status',
        'reference/webhook-faq',
      ],
    },
    {
      type: 'category',
      label: 'Review',
      items: [
        'review/docsai-findings-001',
        'review/docs-map-for-reviewers',
        'review/public-reader-journey',
        'review/editorial-checklist',
      ],
    },

  ],
};

export default sidebars;
